### ISSUE TITLE
drf-tracking incompatible with Django 3+

### ISSUE THREAD

**Issue by eweisner1973** [inputlogic/django-api-starter#61]
This is after a fresh clone of django-api-starter and using Ubuntu OS.

When running migrations and Django version is 3 or greater, following error results:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/env/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/env/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/env/lib/python3.6/site-packages/rest_framework_tracking/models.py", line 1, in <module>
    from .base_models import BaseAPIRequestLog
  File "/env/lib/python3.6/site-packages/rest_framework_tracking/base_models.py", line 3, in <module>
    from django.utils.six import python_2_unicode_compatible
ModuleNotFoundError: No module named 'django.utils.six'

Switching back to Django 2.1.7 allows migrations to work.

**Comment by weslord** [comment]
`drf-tracking` has been abandoned and is no longer supported (see https://github.com/aschn/drf-tracking/), but an updated fork exists called `drf-api-tracking` (https://github.com/lingster/drf-api-tracking) which seems to work.
